name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    
    - name: Change Directory
      run: cd functions
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    name: Deploy
    needs: build
    runds-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
